spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371